// GENERATED CODE - DO NOT MODIFY BY HAND
// dart format width=80

// **************************************************************************
// MCPGenerator
// **************************************************************************

// ignore_for_file: type=lint
part of 'weather_service.dart';

/// Generated extension for [WeatherServiceMCP] that provides automatic registration
/// of all annotated MCP tools, resources, and prompts.
///
/// This code is automatically generated by the MCP Dart framework.
/// Do not modify this file directly - instead, modify the source
/// class and run `dart run build_runner build` to regenerate.
extension WeatherServiceMCPRegistration on WeatherServiceMCP {
  /// Registers all generated handlers for annotated methods.
  /// Call this method in your constructor to automatically register
  /// all MCP tools, resources, and prompts.
  void registerGeneratedHandlers() {
    // Register handler for @MCPTool('get_current_weather')

    registerTool(
      'get_current_weather',
      (context) async {
        final location = context.param<String>('location');
        final unit = context.optionalParam<String>('unit') ?? 'celsius';
        final includeExtended =
            context.optionalParam<bool>('includeExtended') ?? false;
        return await getCurrentWeather(
          location,
          unit: unit,
          includeExtended: includeExtended,
        );
      },
      description: 'Get current weather for a location',
      inputSchema: {
        'type': 'object',
        'properties': {
          'location': {
            'type': 'string',
            'description': 'City name or coordinates',
            'example': 'San Francisco',
          },
          'unit': {
            'type': 'string',
            'description': 'Temperature unit',
            'example': 'celsius',
          },
          'includeExtended': {
            'type': 'boolean',
            'description': 'Include extended forecast',
          },
        },
        'required': ['location'],
      },
    );

    // Register handler for @MCPTool('get_weather_alerts')

    registerTool(
      'get_weather_alerts',
      (context) async {
        final location = context.param<String>('location');
        final severity = context.optionalParam<String?>('severity');
        return await getWeatherAlerts(
          location,
          severity: severity,
          context: context,
        );
      },
      description: 'Get weather alerts for a location',
      inputSchema: {
        'type': 'object',
        'properties': {
          'location': {
            'type': 'string',
            'description': 'Location to check for alerts',
          },
          'severity': {
            'type': 'string',
            'description': 'Alert severity filter',
          },
        },
        'required': ['location'],
      },
    );

    // Register handler for @MCPTool('search_locations')

    registerTool(
      'search_locations',
      (context) async {
        final query = context.param<String>('query');
        final limit = context.optionalParam<int>('limit') ?? 10;
        return await searchLocations(query, limit: limit);
      },
      description: 'Search for weather locations',
      inputSchema: {
        'type': 'object',
        'properties': {
          'query': {
            'type': 'string',
            'description': 'Search query for locations',
          },
          'limit': {
            'type': 'integer',
            'description': 'Maximum number of results',
          },
        },
        'required': ['query'],
      },
    );

    // Register handler for @MCPResource('weather_stations')

    registerResource('weather_stations', (uri) async {
      return await getWeatherStations(uri);
    });

    // Register handler for @MCPPrompt('weather_report')

    registerPrompt('weather_report', (args) {
      return weatherReportPrompt(args);
    });
  }

  /// Generates standardized usage documentation for MCP servers.
  ///
  /// This helper method provides consistent help text formatting
  /// for this specific MCP server with its available capabilities.
  void showUsage({String? serverName}) {
    print('Usage: dart ${serverName ?? "server"}.dart [options]');
    print('');
    print('Options:');
    print('  --stdio        Start server in stdio mode (default)');
    print('  --http         Start HTTP server on port 8080');
    print('  --port <port>  Specify HTTP port (default: 8080)');
    print('  --help, -h     Show this help message');
    print('');
    print(
      'Available tools: get_current_weather, get_weather_alerts, search_locations',
    );
    print('Available resources: weather_stations');
    print('Available prompts: weather_report');
    print('');

    print('Examples:');
    print('  dart ${serverName ?? "server"}.dart');
    print('  dart ${serverName ?? "server"}.dart --http');
    print('  dart ${serverName ?? "server"}.dart --http --port 3000');
  }
}
